RESERVED_WORDS_MAPPING = {
    # Data Types
    # postgres : redshift
    "SMALLINT" :    "SMALLINT",
    "INT2" :        "SMALLINT",
    "INT" :         "INTEGER",
    "INT4" :        "INTEGER",
    "BIGINT" :      "BIGINT",
    "INT8" :        "BIGINT",
    "DECIMAL" :     "DECIMAL",
    "NUMERIC" :     "DECIMAL",
    "REAL" :        "REAL",
    "FLOAT4" :      "REAL",
    "DOUBLE PRECISION" : "FLOAT",
    "FLOAT8" :      "FLOAT",
    "CHARACTER" :   "CHAR",
    "CHAR" :        "CHAR",
    "VARCHAR" :     "VARCHAR",
    "TEXT" :        "VARCHAR",
    "DATE" :        "DATE",
    "TIME" :        "TIME",
    "TIMETZ" :      "TIMETZ",
    "BOOLEAN" :     "BOOLEAN",
    "BOOL" :        "BOOLEAN",
    "TIMESTAMP" :   "TIMESTAMP",
    "TIMESTAMPTZ" : "TIMESTAMPTZ",
    # MOST USED/COMMONS
    # postgres_word : redshift_word
    "AND" :         "AND",
    "AS" :          "AS",
    "ASC" :         "ASC",
    "CASE" :        "CASE \n\t",
    "DESC" :        "DESC",
    "DISTINCT" :    "DISTINCT",
    "ELSE" :        "ELSE",
    "END" :         "END",
    "FALSE" :       "FALSE",
    "FROM" :        "FROM",
    "GROUP" :       "GROUP",
    "IN" :          "IN",
    "INNER" :       "INNER",
    "IS" :          "IS",
    "JOIN" :        "JOIN",
    "LEFT" :        "LEFT",
    "NOT" :         "NOT",
    "NULL" :        "NULL",
    "ON" :          "\n\tON",
    "OR" :          "OR",
    "ORDER" :       "ORDER",
    "RIGHT" :       "RIGHT",
    "SELECT" :      "SELECT \n\t",
    "THEN" :        "\n\t\tTHEN",
    "WHEN" :        "\tWHEN",
    "WHERE" :       "WHERE",
    "WITH" :        "WITH",
    # Postgres Functions
    # postgres_word : redshift_word
    # "" : "AES128",
    # "" : "AES256",
    "ALL" : "ALL",
    # "" : "ALLOWOVERWRITE",
    # "" : "ANALYSE",
    # "" : "ANALYZE",
    "ANY" : "ANY",
    # "" : "ARRAY",
    # "" : "AUTHORIZATION",
    # "" : "AZ64",
    # "" : "BACKUP",
    "BETWEEN" : "BETWEEN",
    # "" : "BINARY",
    # "" : "BLANKSASNULL",
    "BOTH" : "BOTH",
    "BY" : "BY",
    # "" : "BYTEDICT",
    # "" : "BZIP2",
    "CAST" : "CAST",
    "CHECK" : "CHECK",
    "COLLATE" : "COLLATE",
    "COLUMN" : "COLUMN",
    "CONSTRAINT" : "CONSTRAINT",
    "CREATE" : "CREATE",
    # "" : "CREDENTIALS",
    "CROSS" : "CROSS",
    "CURRENT_DATE" : "CURRENT_DATE",
    "CURRENT_TIME" : "CURRENT_TIME",
    "CURRENT_TIMESTAMP" : "CURRENT_TIMESTAMP",
    "CURRENT_USER" : "CURRENT_USER",
    # "" : "CURRENT_USER_ID",
    "DEFAULT" : "DEFAULT",
    # "" : "DEFERRABLE",
    # "" : "DEFLATE",
    # "" : "DEFRAG",
    # "" : "DELTA",
    # "" : "DELTA32K",
    # "" : "DISABLE",
    # "" : "DO",
    # "" : "EMPTYASNULL",
    # "" : "ENABLE",
    # "" : "ENCODE",
    # "" : "ENCRYPT     ",
    # "" : "ENCRYPTION",
    "EXCEPT" : "EXCEPT",
    # "" : "EXPLICIT",
    "FOR" : "FOR",
    "FOREIGN" : "FOREIGN",
    # "" : "FREEZE",
    "FULL" : "FULL",
    # "" : "GLOBALDICT256",
    # "" : "GLOBALDICT64K",
    "GRANT" : "GRANT",
    # "" : "GZIP",
    "HAVING" : "HAVING",
    # "" : "IDENTITY",
    # "" : "IGNORE",
    # "" : "ILIKE",
    # "" : "INITIALLY",
    "INTERSECT" : "INTERSECT",
    "INTERVAL" : "INTERVAL",
    "INTO" : "INTO",
    # "" : "ISNULL",
    "LEADING" : "LEADING",
    "LIKE" : "LIKE",
    # "" : "LIMIT",
    # "" : "LOCALTIME",
    # "" : "LOCALTIMESTAMP",
    # "" : "LUN",
    # "" : "LUNS",
    # "" : "LZO",
    # "" : "LZOP",
    # "" : "MINUS",
    # "" : "MOSTLY16",
    # "" : "MOSTLY32",
    # "" : "MOSTLY8",
    "NATURAL" : "NATURAL",
    # "" : "NEW",
    # "" : "NOTNULL",
    # "" : "NULLS",
    # "" : "OFF",
    # "" : "OFFLINE",
    # "" : "OFFSET",
    # "" : "OID",
    # "" : "OLD",
    # "" : "ONLY",
    # "" : "OPEN",
    "OUTER" : "OUTER",
    "OVERLAPS" : "OVERLAPS",
    # "" : "PARALLEL",
    # "" : "PARTITION",
    # "" : "PERCENT",
    # "" : "PERMISSIONS",
    # "" : "PIVOT",
    # "" : "PLACING",
    "PRIMARY" : "PRIMARY",
    # "" : "RAW",
    # "" : "READRATIO",
    # "" : "RECOVER",
    "REFERENCES" : "REFERENCES",
    # "" : "REJECTLOG",
    # "" : "RESORT",
    # "" : "RESPECT",
    # "" : "RESTORE",
    "SESSION_USER" : "SESSION_USER",
    # "" : "SIMILAR",
    # "" : "SNAPSHOT ",
    "SOME" : "SOME",
    # "" : "SYSDATE",
    # "" : "SYSTEM",
    "TABLE" : "TABLE",
    # "" : "TAG",
    # "" : "TDES",
    # "" : "TEXT255",
    # "" : "TEXT32K",
    # "" : "TIMESTAMP",
    "TO" : "TO",
    # "" : "TOP",
    "TRAILING" : "TRAILING",
    "TRUE" : "TRUE",
    # "" : "TRUNCATECOLUMNS",
    "UNION" : "UNION",
    "UNIQUE" : "UNIQUE",
    # "" : "UNNEST",
    # "" : "UNPIVOT",
    "USER" : "USER",
    "USING" : "USING",
    # "" : "VERBOSE",
    # "" : "WALLET",
    # "" : "WITHOUT"
}